name: App CI

on:
  push:
    paths: ['**.json', '**.js', '**.ts']
  workflow_dispatch:

jobs:
  build:
    name: Build and lint on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup node and restore cached dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install packages
        run: yarn --prefer-offline

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
